[package]
name = "movie-site"
version = "0.1.0"
authors = ["richard.thomas <richard.thomas@interfront.co.za>"]

[dependencies]
rocket = "0.3.8"
rocket_codegen = "0.3.8"
csv = "1.0.0-beta.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0.45"